dbus-c++: Rename to_string to make_string to build with libc++.
Source files have an using namespace std;
So the to_string function conflicts with std::to_string function.
Rename it to make_string to avoid compilation errors with libc++.

generate_stubs.cpp:90:17: error: call to 'to_string' is ambiguous
                                        ("argin" + to_string(i)) : legalize(arg_name);
                                                   ^~~~~~~~~
/usr/bin/../include/c++/v1/string:3881:25: note: candidate function
_LIBCPP_FUNC_VIS string to_string(unsigned __val);
                        ^
./generator_utils.h:38:13: note: candidate function
std::string to_string(unsigned int v);

BUG=chromium:747030
TEST=sudo emerge dbus-c++ works with libc++ enabled.

Change-Id: I09a058b9bc83c70b4caab9a57ee2d74ff02ba320
Reviewed-on: https://chromium-review.googlesource.com/580330
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Ben Chan <benchan@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>